### ISSUE TITLE
стоимость доставки в калининград должна учитываться в общем итоге, но не должна участвовать в возврате таксфри

### ISSUE THREAD

**Issue by lemonleks** [reviakin/IMSERVICE-form#14]
![image](https://user-images.githubusercontent.com/6837579/60731729-95ba7f80-9f48-11e9-9ba9-3357baa890d4.png)

**Comment by lemonleks** [comment]
получил подтверждение от клиента "сумма доставки в Калининград не идет в таксфри "

**Comment by reviakin** [comment]
Я правильно понял:

a3476a0

**Comment by reviakin** [comment]
Я добавил комент для тебя строчка 333 :)

**Comment by reviakin** [comment]
4b1a599
a3476a0

**Comment by lemonleks** [comment]
отлично! давай ещё скроем строку про возврат такс фри при доставке в калининград, раз уж мы его клиенту не делаем

**Comment by reviakin** [comment]
e81089b
