### ISSUE TITLE
Расчёт итоговых значений

### ISSUE THREAD

**Issue by lemonleks** [reviakin/IMSERVICE-form#7]
формула возврата такая:
сумма к оплате PLN =(цена товара+цена доставки)* 1,12
возврат ват = сумма к оплате - (сумма к оплате/1,23)

доставка в Калининград = 
до 2 кг - 700 р 
2-5 -1000 р 
5-10 кг 1300 руб
свыше 10 кг = 100 руб за кг, но минимум 1300

в общей сумме её нужно учесть переведя по курсу в злотые.

в рубли пока переводим по курсу 16,9, но сделай так, чтобы потом можно было легко подставить глобальную переменную, которая будет добавляться в index.html при загрузке страницы, там будет актуальный курс.

**Comment by reviakin** [comment]
closed #4a45327

**Comment by reviakin** [comment]
closed 4a45327
