### ISSUE TITLE
во время ошибки валидации в цене съезжает PLN

### ISSUE THREAD

**Issue by lemonleks** [reviakin/IMSERVICE-form#9]
и "цена brutto" лишняя n
![image](https://user-images.githubusercontent.com/6837579/60729141-4a9d6e00-9f42-11e9-8c30-b051e824644e.png)

**Comment by lemonleks** [comment]
в инпуте с весом то же самое

![image](https://user-images.githubusercontent.com/6837579/60729801-d95eba80-9f43-11e9-96fe-2f2253a84d6f.png)

**Comment by reviakin** [comment]
closed #d0f8ed9
